# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=220, null=True)),
                ('project', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.FileField(upload_to=b'')),
                ('Description', models.TextField()),
                ('Course_period', models.CharField(max_length=220)),
                ('Publish', models.DateField(blank=True)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=220)),
                ('Video', models.FileField(upload_to=b'')),
                ('Publish', models.DateField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineprogram.project_category')),
                ('title_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlineprogram.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineprogram.project_category'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
