# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
