# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineprogram', '0002_project_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
