# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineprogram', '0003_project_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
